---
- name: Deploy Portainer via Docker Compose
  docker_compose_v2:
    project_name: portainer
    definition:
      services:
        portainer:
          image: portainer/portainer-ce:latest
          restart: always
          ports:
            - "9000:9000"
            - "9443:9443"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /mnt/store/data/portainer:/data
