---
- name: Deploy NATS via Docker Compose
  docker_compose_v2:
    project_name: nats
    definition:
      services:
        nats:
          image: nats:latest
          restart: always
          ports:
            - "4222:4222"   # client connections
            - "8222:8222"   # monitoring UI
          command: >
            -js
            -sd /data
            -m 8222
          volumes:
            - /mnt/store/data/nats:/data
